### ISSUE TITLE
[Server]Настроить вспомогательные команды

### ISSUE THREAD

**Issue by Veleri** [yehormonko/IMessanger#17]
При запуске сервера можно воспользоваться командой /help, после чего становятся доступны команды:
-/online  - добавить сообщение, на случай отсутствия пользователей;
-/admin - при использовании команды получаем ошибки индексов. 
Например:
#/admin
Exception in thread "Thread-1" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1967)
        at Server.commands(Server.java:88)
        at Server$2.run(Server.java:124)

**Comment by yehorsyrin** [comment]
Команды настроены в коммите #17 closed
